[profile.default]
auto_detect_remappings = true
broadcast = "contracts/broadcast"
cache_path = "contracts/cache"
libs = ["contracts/lib"]
no_match_coverage = "contracts/script"
out = "contracts/out"
remappings = [
  "forge-std/=contracts/lib/forge-std/src/",
  "src/=contracts/src/",
  "test/=contracts/test/",
]
solc = "0.8.28"
script = "contracts/script"
src = "contracts/src"
test = "contracts/test"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
localhost = "${ANVIL_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
