[profile.default]
auto_detect_remappings = true
broadcast = "contracts/broadcast"
cache_path = "contracts/cache"
libs = ["contracts/lib"]
no_match_coverage = "contracts/script"
out = "contracts/out"
remappings = [
  "forge-std/=contracts/lib/forge-std/src/",
  "src/=contracts/src/",
  "test/=contracts/test/",
]
script = "contracts/script"
src = "contracts/src"
test = "contracts/test"
