name: main
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR coveralls comments
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_sol_changed: ${{ steps.filter.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: |
            foundry.toml
            contracts/**/*.sol

  _tests:
    needs: changed-files
    if: needs.changed-files.outputs.any_sol_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge soldeer update
      - run: forge coverage --report lcov --report-file lcov.info
      - uses: coverallsapp/github-action@v2.3.0
        with:
          format: lcov
          file: lcov.info

  tests:
    needs: _tests
    if: ${{ !(failure() || cancelled()) }}
    runs-on: ubuntu-latest
    steps:
      - name: Tests OK (passed or skipped
        run: exit 0

  # no need to bother caching bun deps
  # https://github.com/oven-sh/setup-bun/issues/14#issuecomment-1714116221
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            "check:format" = { run = "dprint check --excludes mise.toml" }
            #FIXME
            #"check:lint-sol" = { dir = "contracts", run = "solhint --config contracts/.solhint.json --ignore-path contracts/.solhintignore contracts/**/*.sol" }
            "check:lint-ts" = { run = "biome lint --config-path=.biome.jsonc --no-errors-on-unmatched" }
            "check:types" = { run = "tsc -p web/tsconfig.app.json" }
            check = { depends = "check:*" }
            [tools]
            bun = "latest"
            dprint = "latest"
            "npm:@biomejs/biome" = "latest"
            "npm:solhint" = "latest"
            "npm:typescript" = "latest"
             "cargo:https://github.com/foundry-rs/foundry" = { version = "tag:stable", crate = "forge" }
      - run: bun i
      - run: mise check
